### ISSUE TITLE
MultClass classifier

### ISSUE THREAD

**Issue by Atma9** [intel/daal#27] opened 2017-07-25 16:09 UTC
Hi,

The multiclass-classifier requires binary classifier like SVM, but fails when assigning any of the others like adaboost, logitboost etc... Is this as expected? 

Additionally attemp to serialize KNN model returns no error at start, but clearly causes memory corruption. 

Thanks!
Atma

**Comment by Vika-F** [comment] 2017-07-27 08:02
@Atma9, Our analysis shown that the issue with KNN model serialization is not reproduced with DAAL 2018 Beta Update 1. If you are using an older version of DAAL, can you please check on your side that the issue is fixed in DAAL 2018 Beta Update 1?

The issue with multi-class classifier was reproduced on our side. We will work to fix it in the future releases of the library.

Best regards,
Victoriya

**Comment by OlegKremnyov** [comment] 2018-02-16 13:37
@Atma9, the issue with multi-class classifier was fixed in DAAL 2018 Update 1.

**Closed** 2018-02-25 08:09 UTC
