### ISSUE TITLE
Decision Forest prediction provides wrong result if algorithm and result datatypes do not match

### ISSUE THREAD

**Issue by Mightrider** [intel/daal#271] opened 2020-01-15 09:53 UTC
Hi!

**Describe the bug**
I want to use shallow copies of my own memory for my classification to avoid copying data. For the data input that works fine. To get the predicted results I create a prediction::ResultPtr and set a NumericalTablePtr with my own memory. If the daalDataType and the resultDataType are the same I get the expected results. If the resultDataType differs only the first element in my array is changed. The rest seems to stay the same. 

I tried the same procedure with SVM and there the results are correct if the datatypes mismatch. 

**To Reproduce**
```c++
#include <daal.h>
#include <service.h>

int main(){
    const size_t nClasses = 2;

    typedef int dataType;
    typedef double daalDataType;
    typedef float resultDataType;

    /* creating arrays for shallow data access */
    dataType vData[8] = { 0, 0, 0, 1, 1, 0, 1, 1 };
    dataType vLabels[4] = { 0, 1, 1, 0 };

    dataType vTestData[8] = { 0, 1, 1, 0, 0, 0, 1, 1 };
    dataType vTestLabels[4] = { 1, 1, 0, 0 };

    resultDataType vResultsMemory[4] = { -1, -1, -1, -1 };

    const size_t vPrintLines = 4;

    using namespace daal;
    using namespace daal::algorithms;
    using namespace daal::data_management;
    using namespace daal::algorithms::decision_forest::classification;

    /* Create Numeric Tables for training data and labels with the data pointer of xtensor */
    NumericTablePtr vTrainData(HomogenNumericTable<dataType>::create(vData, 2, 4));
    NumericTablePtr vTrainGroundTruth(HomogenNumericTable<dataType>::create(vLabels, 1, 4));

    printNumericTables<dataType, dataType>(vTrainData, vTrainGroundTruth, "Train features:", "Train labels:", "Check data:", vPrintLines);

    /* Create an algorithm object to train the decision forest classification model */
    training::Batch<daalDataType> vTrainingBatch(nClasses);

    vTrainingBatch.parameter.nTrees = 4;
    vTrainingBatch.parameter.varImportance = algorithms::decision_forest::training::MDI;
    vTrainingBatch.parameter.resultsToCompute = algorithms::decision_forest::training::computeOutOfBagError;


    /* Pass a training data set and dependent values to the algorithm */
    vTrainingBatch.input.set(classifier::training::data, vTrainData);
    vTrainingBatch.input.set(classifier::training::labels, vTrainGroundTruth);

    /* Build the model */
    vTrainingBatch.compute();

    std::cout << "Training Complete" << std::endl;

    /**
     * Predict using the trained model
     */
    NumericTablePtr vNumTestData(HomogenNumericTable<dataType>::create(vTestData, 2, 4));
    NumericTablePtr vNumTestLabels(HomogenNumericTable<dataType>::create(vTestLabels, 1, 4));


    prediction::Batch<daalDataType> vPredictorBatch(nClasses);

    vPredictorBatch.input.set(classifier::prediction::model, vTrainingBatch.getResult()->get(classifier::training::model));
    /* Pass a testing data set and the trained model to the algorithm */
    vPredictorBatch.input.set(classifier::prediction::data, vNumTestData);

    // We want to get the result in xtensor memory, so first we create a shallow NumericTablePtr
    NumericTablePtr vPredictedLabels(HomogenNumericTable<resultDataType>::create(vResultsMemory, 1, 4));
    // we create a new resultPtr
    classifier::prediction::ResultPtr vResultPtr(new classifier::prediction::interface1::Result());

    // and assign our shallow NumericTablePtr to the prediction
    vResultPtr->set(classifier::prediction::prediction, vPredictedLabels);
    vPredictorBatch.setResult(vResultPtr);

    /* Predict the values */
    vPredictorBatch.compute();

    /* Retrieve the algorithm results */
    printNumericTables<int, int>(vNumTestLabels, vPredictorBatch.getResult()->get(classifier::prediction::prediction),
                                 "Expected results", "Prediction results",
                                 "classification sample program results:", vPrintLines);

    // Thanks to our shallow copy we can directly access the results in vPredictedLabels
    for (size_t i = 0; i < 4; i++) {
        std::cout << vResultsMemory[i] << std::endl;
    }
}
```

**Expected behavior**
Results I get:
```
classification sample program results:
Expected resultsPrediction results
1              1              
1              -1             
0              -1             
0              -1 
```

Results I expect (result for matching datatypes):
```
classification sample program results:
Expected resultsPrediction results
1              1              
1              0              
0              1              
0              0
```

**Environment:**
 - OS: [Ubuntu 18.04]
 - Compiler: [GCC7.4]
 - Version: [2019 Update 5]

**Comment by ShvetsKS** [comment] 2020-01-27 14:30
Hello, thanks for reporting this bug.

Fix was already applied as part of https://github.com/intel/daal/pull/294.

The problem was due to wrong number of rows to be read form result:

`WriteOnlyRows<algorithmFPType, cpu> resBD(_res, 0, 1);` -> 
`WriteOnlyRows<algorithmFPType, cpu> resBD(_res, 0, nRows);`

After fix was implemented we can obtain expected result:
```
Training Complete
classification sample program results:
Expected resultsPrediction results

1                         1
1                         0
0                         1
0                         0
```

**Comment by ShvetsKS** [comment] 2020-01-29 12:30
Thanks a lot for finding this bug and valuable contribution to DAAL project.
Fix has been merged to master, releases and rls/daal-2020-mnt branches.
As inference results are expected now via provided reproducer we close this issue but if you have any concerns please reopen it.

**Closed by ShvetsKS** 2020-01-29 12:30 UTC
Labels: bug
